//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoGo_Tester.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoGo_Tester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ARSoft_Tools_Net {
            get {
                object obj = ResourceManager.GetObject("ARSoft_Tools_Net", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon GoGo_logo {
            get {
                object obj = ResourceManager.GetObject("GoGo_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 1.179.248-255.0-255
        ///103.246.187.0-255
        ///103.25.178.4-59
        ///106.162.192.148-187
        ///106.162.198.84-123
        ///106.162.216.20-123
        ///107.167.160-191.0-255
        ///107.178.192-255.0-255
        ///107.188.128-255.0-255
        ///108.170.192-255.0-255
        ///108.177.0-127.0-255
        ///108.59.80-95.0-255
        ///109.232.83.64-127
        ///111.168.255.20-187
        ///111.92.162.4-59
        ///113.197.105-106.0-255
        ///118.174.24-27.0-255
        ///12.216.80.0-255
        ///121.78.74.68-123
        ///123.205.250-251.68-190
        ///130.211.0-255.0-255
        ///130.211.0-255.0-255
        ///142.250-251.0-255.0-255
        ///146.148.0-127.0-255
        ///149.126.86.1-5 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string InnerIpSet {
            get {
                return ResourceManager.GetString("InnerIpSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Windows_Ding {
            get {
                return ResourceManager.GetStream("Windows_Ding", resourceCulture);
            }
        }
    }
}
